### ISSUE TITLE
Implement authentication for web app

### ISSUE THREAD

**Issue by rahij** [LagerApp/Lager#16]

**Comment by jin** [comment]
Stick to username/password?

SSL -> Build script to generate self-signed cert?

**Comment by rahij** [comment]
Yeah username/password should be fine. Or we can send a token to the server on every request. What do you think?

**Comment by jin** [comment]
Yep let’s go with token based auth.

How about this flow to get rid of username/passwords entirely?

1) Set up app on server
2) Have build script provide auth tokens displayed as strings or QR-code (
https://www.npmjs.com/package/qrcode-terminal)
3) On the clientside, enter auth code durectly or use
https://github.com/LazarSoft/jsqrcode + HTML5 Camera API to decode QR-code
